openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/fbv/hello:
    get:
      operationId: listhellos
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
  /api/fbv/contacts:
    get:
      operationId: listcontacts
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
  /api/cbv/contacts:
    get:
      operationId: listContacts
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
          description: ''
      tags:
      - api
    post:
      operationId: createContact
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Contact'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
          description: ''
      tags:
      - api
  /api/cbv/contacts/{id}:
    get:
      operationId: retrieveContact
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: Unique ID of this contact
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
          description: ''
      tags:
      - api
    put:
      operationId: updateContact
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: Unique ID of this contact
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Contact'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateContact
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: Unique ID of this contact
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Contact'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyContact
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: Unique ID of this contact
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/cbv/cities:
    get:
      operationId: listCitys
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/City'
          description: ''
      tags:
      - api
    post:
      operationId: createCity
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/City'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/City'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/City'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
          description: ''
      tags:
      - api
  /api/cbv/cities/{id}:
    get:
      operationId: retrieveCity
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: Unique ID of this city
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
          description: ''
      tags:
      - api
    put:
      operationId: updateCity
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: Unique ID of this city
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/City'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/City'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/City'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateCity
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: Unique ID of this city
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/City'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/City'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/City'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyCity
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: Unique ID of this city
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/contacts/:
    get:
      operationId: listContacts
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
          description: ''
      tags:
      - api
    post:
      operationId: createContact
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Contact'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
          description: ''
      tags:
      - api
  /api/contacts/{id}/:
    get:
      operationId: retrieveContact
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: Unique ID of this contact
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
          description: ''
      tags:
      - api
    put:
      operationId: updateContact
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: Unique ID of this contact
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Contact'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateContact
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: Unique ID of this contact
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Contact'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyContact
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: Unique ID of this contact
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/cities/:
    get:
      operationId: listCitys
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/City'
          description: ''
      tags:
      - api
    post:
      operationId: createCity
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/City'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/City'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/City'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
          description: ''
      tags:
      - api
  /api/cities/{id}/:
    get:
      operationId: retrieveCity
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: Unique ID of this city
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
          description: ''
      tags:
      - api
    put:
      operationId: updateCity
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: Unique ID of this city
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/City'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/City'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/City'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateCity
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: Unique ID of this city
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/City'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/City'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/City'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyCity
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: Unique ID of this city
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
components:
  schemas:
    Contact:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          description: Unique ID of this contact
        first_name:
          type: string
          description: First name
          maxLength: 32
        last_name:
          type: string
          description: Last name
          maxLength: 32
        street_address:
          type: string
          nullable: true
          description: Street address
          maxLength: 32
        city:
          type: string
          readOnly: true
        postcode:
          type: string
          nullable: true
          description: Postal code (Zip, etc)
          maxLength: 16
        dob:
          type: string
          format: date
          nullable: true
          description: Date of birth
      required:
      - first_name
      - last_name
    City:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          description: Unique ID of this city
        name:
          type: string
          description: City name
          maxLength: 64
        admindiv:
          type: string
          nullable: true
          description: Administrative Division (State/Province etc.)
          maxLength: 128
        country:
          type: string
          description: Country code
          maxLength: 2
      required:
      - name
